version: '3'
services:
  web:
    build: .
    volumes:
      - ".:/web"
    ports:
      - "3000:3000"
    depends_on:
      - db
    working_dir: "/web"
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "mysql-data:/var/lib/mysql"

volumes:
  mysql-data:
    driver: local
